name: noted_models
description: A collection of models for use in the Noted ecosystem.
version: 0.0.1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  dart_mappable: ^4.0.1

dev_dependencies:
  build_runner: ^2.4.5
  dart_mappable_builder: ^4.0.1

  noted_lints:
    git:
      url: https://github.com/NotedApp/noted_lints.git
      ref: v1.0.2

  test: ^1.21.0

